# Generated by Django 3.0.5 on 2020-04-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='date',
            new_name='creation_date',
        ),
    ]
