# Generated by Django 3.0.5 on 2020-04-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_app', '0002_auto_20200415_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
